### ISSUE TITLE
Add ipylayout to conda-forge?

### ISSUE THREAD

**Issue by giswqs** [davidbrochart/ipylayout#1]
It would be great if you can make ipylayout available on conda-forge. I might add it as a dependency for the geemap package.

**Comment by davidbrochart** [comment]
I will, but please note that ipylayout is very early stage right now. Also, you can still install with `pip` in a conda environment, as we do in Binder: https://github.com/davidbrochart/ipylayout/blob/0fd6b9ce21fc6f564f1872c973b7ac4eba320f0f/environment.yml

**Comment by davidbrochart** [comment]
It can now be installed with conda: `conda install -c conda-forge ipylayout`
